### ISSUE TITLE
Blog posts are infinitely repeating.

### ISSUE THREAD

**Issue by jdmcreative** [jdmdigital/bootplate#72]
This is the error on the blog page: 

Fatal error: Maximum execution time of 30 seconds exceeded in /home/content/63/9182463/html/rw2016/wp-includes/formatting.php on line 588

Link to Blog:[http://rw2016.ratedgenius.com/blog/]

**Comment by jdmdigital** [comment]
That's a bug in the posts listing page template.  We're working on a fix to be released in v1.3 (coming very soon).  In the meantime, use links to the category instead of setting a Posts Page.

**Comment by jdmdigital** [comment]
Fix made, we think, in https://github.com/jdmdigital/bootplate/commit/e4848b7a0a57ace90c028036581f4f6ec155709e but we're going to test overnight and release tomorrow.

**Comment by jdmdigital** [comment]
Example with fix applied: http://bootplate.jdmdigital.co/templates/post-page/

**Comment by jdmdigital** [comment]
Seems to be working fine now in the development branch. The problem was nested while have_posts loops.
